version: "3.5"
services:
  nginx-api:
    container_name: api-nginx
    env_file: .env
    build:
        dockerfile: app-nginx-api
        context: .
    volumes:
    - ./api:/var/www/html
    ports:
    - "80"
    links:
    - php
  php:
    container_name: api-php
    env_file: .env
    build:
        dockerfile: app-php
        context: .
    volumes:
    - ./api:/var/www/html
    links:
    - mysql
  frontend:
    container_name: ui-nginx
    env_file: .env
    build:
        dockerfile: app-nginx-frontend
        context: .
    volumes:
    - ./frontend:/var/www/html
    ports:
    - "80"
  mysql:
    container_name: mysql
    env_file: .env
    image: mysql:8
    ports:
    - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: ${db_password}
