version: '3'
services:
  nginx-api:
    build:
        dockerfile: app-nginx-api
        context: .
    volumes:
    - ./api:/var/www/html
    ports:
    - 43080:80
    links:
    - php
  php:
    build:
        dockerfile: app-php
        context: .
    volumes:
    - ./api:/var/www/html
    links:
    - mysql
  frontend:
    build:
        dockerfile: app-nginx-frontend
        context: .
    volumes:
    - ./frontend:/var/www/html
    ports:
    - 43081:80
  mysql:
    image: mysql:8.0.13
    ports:
    - 43006:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: root
